-- Initial
DROP TABLE IF EXISTS ITEMS;

DROP TABLE IF EXISTS ORDERS;

CREATE TABLE IF NOT EXISTS ITEMS (
    NAME VARCHAR(255) NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 10
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ITEM_NAME VARCHAR(255) NOT NULL,
    NUMBER INT NOT NULL
);

INSERT INTO ITEMS (
    NAME
) VALUES (
    "apple"
),
(
    "pineapple"
),
(
    "pear"
);