-- Creating a trigger that triggers
-- ?? when a new order inserted


CREATE TRIGGER DECREASE_QUANTITY AFTER
    INSERT ON ORDERS FOR EACH ROW
        UPDATE ITEMS SET QUANTITY = QUANTITY - NEW.NUMBER WHERE NAME = NEW.ITEM_NAME;