-- Rests valid_email when email changed
DELIMITER $$

DROP TRIGGER IF EXISTS REST_VALID_EMAIL;

CREATE TRIGGER REST_VALID_EMAIL BEFORE
    UPDATE ON USERS FOR EACH ROW
BEGIN
    IF NEW.EMAIL <> OLD.EMAIL THEN
        SET NEW.VALID_EMAIL = 0;
    END IF;
END $$