-- Rests valid_email when email changed

DELIMITER $$

CREATE TRIGGER NEW_EMAIL BEFORE
    UPDATE ON USERS FOR EACH ROW
BEGIN
    IF OLD.EMAIL != NEW.EMAIL THEN
        SET NEW.VALID_EMAIL = 0;
    END IF;
    END$$ DELIMITER;