-- Creates a stored procedure
-- ComputeOverallScoreForUser

DELIMITER $$

DROP PROCEDURE IF EXISTS COMPUTEAVERAGESCOREFORUSER;

CREATE PROCEDURE COMPUTEAVERAGESCOREFORUSER (
    IN USER_ID INT
)
BEGIN
    UPDATE USERS
    SET
        AVERAGE_SCORE = (
            SELECT AVG(SCORE) FROM CORRECTIONS WHERE CORRECTIONS.USER_ID = USER_ID
        )
    WHERE
        ID = USER_ID;
END $$ DELIMITER;